### ISSUE TITLE
Mincraft doesn't work

### ISSUE THREAD

**Issue by jera0202** [JamStudios/DynamicClient#36]
I've insstaled the newest version, but when i launch minecraft (1.16.5), it don't response
![minecraft lagging](https://user-images.githubusercontent.com/74967809/151042602-8787dcde-5900-4ad2-837d-e3f333968795.png)

**Comment by JamTheAdventurer** [comment]
Please Answer these questions:
- Proccessor:
- RAM:
- Storage:
- What launcher are you using?
- What Dynamic Client Version you are using?

**Comment by JamTheAdventurer** [comment]
We're sorry jera0202, but you where unresponsive for the last 5 days, Unresponded Issues will automatically be closed. 

Solution:
As given questions we're not answered and is unrespondant, we have no clue of how we may help you as this is a system problem and or have a low spec Desktop/Laptop, We recommend using Powershell Toolbox to optimize your Windows 10 Desktop /Laptop: https://youtu.be/uOf_wH6jSEE

If the solutions that we gave we're not as affective feel free to reopen this issue, If there is no response/confirmation of success/failure or anything at all we'll just guess it is resolved.
---------------
This issue will be permanently be locked when there is no response until February 4th 2022. 
---------------

- JamStudios Support, Jam The Adventurer
