### ISSUE TITLE
Video player 

### ISSUE THREAD

**Issue by riszamohamad4** [JamStudios/DynamicClient#42]
![49bde1628940aabe6bcd06ae72d29c27](https://github.com/JamStudios/DynamicClient/assets/133600642/2ded48b9-c5d6-41e2-834d-1f80658903b4)
[Video player](Itanriszac@outlook.co.id) **Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by riszamohamad4** [comment]
Conflict disparate

**Comment by JamTheAdventurer** [comment]
Who arre you?
