### ISSUE TITLE
The Script {workshop} does not have credits

### ISSUE THREAD

**Issue by riszamohamad4** [JamStudios/DynamicClient#46]
-- In Order for your creditational submission of this script to be validated you must complete the following questions.
#### Questions (Required):
- i ) What is your Forum Username (Where you posted the script)

- ii ) What is the url of the forum post (etc.. v3rmillion.net/showthread.php?tid=123456)?

- vi ) Your Discord Username#0000, We will send you a friend request and a message for the next verification process 
(Only Reply to this account: JamStudiosCorporation#5996 | Active in Monday - Friday, 9:00 AM to 6:00 PM Philipine Standard Time.)

Please Note: That This GiveCredit issue only last up to 3 Days after the first response to the issue, until this issue is deleted for Privacy & Security Purposes, If You Did not get a response after 3 Days, you may wan't to Close the issue and try again.

**Comment by JamTheAdventurer** [comment]
**JamStudios System**

Warning ⚠: [1/3]
-----------
**Warning**: @riszamohamad4
Please do not Issue Spam a Discontinued Project **(DynamicClient)**

You have made [5] Unnecessary Issues fro the last Hour, Suspected as Botting / Spamming. 

To Avoid your Issues being Flagged as Spam, Please provide adequate information, Based on the Issues: **Uses of the Default Issue Templates.**  

You currently have 1 strike, If you continue to do so until 3 strikes for the next 365 days Your Account will be **Blocked** by the Organization, until further notice. 

If you think this is a mistake contact: jamstudios.corp@hotmail.com

-----------
JSS 


{ This An Auto-Generated Comment, Do not expect a response from this comment onward }
